apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rmq01
  name: rmq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmq01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rmq01
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rmq-secret
                  key: RABBITMQ_DEFAULT_PASS
          ports:
            - name: rmq-amqp
              containerPort: 5672
            - name: rmq-tls
              containerPort: 5671
