apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web01
  name: web01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web01
    spec:
      initContainers:
        - name: generate-ssl
          image: nginx
          command:
            - sh
            - -c
            - |
              openssl req -x509 -newkey rsa:4096 \
                -keyout /data/key.pem \
                -out /data/cert.pem \
                -sha256 -days 3650 -nodes \
                -subj "/C=EG/ST=Cairo/L=Cairo/O=GoApplication/OU=ITservice/CN=www.goapplication.com"
          volumeMounts:
            - name: nginx-config
              mountPath: /data

        - name: setup-nginx-config
          image: nginx
          command:
            - sh
            - -c
            - |
              cat <<'EOF' > /data/nginx.conf
              events { worker_connections 1024; }

              http {
                upstream vproapp {
                  server app01:8080;
                }

                server {
                  listen 80;
                  return 301 https://$host$request_uri;
                }

                server {
                  listen 443 ssl;

                  ssl_certificate     /etc/nginx/ssl/cert.pem;
                  ssl_certificate_key /etc/nginx/ssl/key.pem;

                  location / {
                    proxy_pass http://vproapp;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                  }
                }
              }
              EOF
          volumeMounts:
            - name: nginx-config
              mountPath: /data

      containers:
        - name: nginx
          image: nginx:1.29.3
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/ssl/cert.pem
              subPath: cert.pem
            - name: nginx-config
              mountPath: /etc/nginx/ssl/key.pem
              subPath: key.pem

      volumes:
        - name: nginx-config
          emptyDir: {}
